### ISSUE TITLE
create an internal sequence for more robusteness to order.

### ISSUE THREAD

**Issue by mikemoore13** [whyolet/safe_int_id#1]
When generting ids in a loop, if there less than 1 micro second between two generations the order could be lost.
Why not adding a static int counter incremented each time ? So that we will be sure if executed in the same thread that the order is safe. This create too much collisions
```  
test('order test', () {
      List<int> ids = [];
      for(int i = 0; i < 10000; i++)
      {
        ids.add(safeIntId.getId()); 
      }

      for(int i = 0; i < ids.length - 1; i++)
      {
        expect(ids[i] < ids[i+1], true);
      }

    });
    
````    
maybe this code:

````
library safe_int_id;

import "dart:math";

class SafeIntId {
  late final int firstYear;
  late final int _firstYearMillis;
  late int counter;
  late final Random random;

  SafeIntId({
    this.firstYear = 2023,
    int counter = 0,
    Random? random,
  }) {
    _firstYearMillis = DateTime.utc(firstYear).millisecondsSinceEpoch;
    this.counter = counter;
    this.random = random ?? Random();
  }

  int getId() {
    final millis = DateTime.now().millisecondsSinceEpoch - _firstYearMillis;
    return millis * 100000 + counter++ * 10 + random.nextInt(10);
//reset the counter at some point here
TODO
  }

  DateTime getCreatedAt(int id, {bool isUtc = false}) =>
      DateTime.fromMillisecondsSinceEpoch(
        (id ~/ 100000) + _firstYearMillis,
        isUtc: isUtc,
      );
}

final safeIntId = SafeIntId();

void main() {
  List<int> ids = [];
  for (int i = 0; i < 10000; i++) {
    ids.add(safeIntId.getId());
  }

  for (int i = 0; i < ids.length - 1; i++) {
    assert(ids[i] < ids[i + 1]);
  }
  print("Order test passed!");
}

**Comment by denis-ryzhkov** [comment]
Thank you @mikemoore13!

I've implemented your request a bit differently, but hopefully it covers your needs: please review the changes https://github.com/whyolet/safe_int_id/commit/4812a4bfe3c2c6ce95ef8dab287bfe5d44a749b8 and try using [safe_int_id 1.1.0](https://pub.dev/packages/safe_int_id) with `incId()` and `await incIdAsync()` as alternative for `getId()`.

There is not enough space in an int for a timestamp, and both a counter and a random value - if we want them to be helpful. So for a case like yours (and I will use it in my app too), just having a timestamp + counter with a bigger range of values works better and keeps the code simple and predictable regarding the number of years this ID will still be a safe int.

Please let me know if it works for you.

**Comment by mikemoore13** [comment]
your implem is correct, some subject to discuss for further improvement :
why not putting the timestamp in seconds (32bits) + incremental seq (16 bits) + random part (16 b)  -> 64 = 32 + 16 +16
if you are going async, (should be also valid for sync code), maybe adding a lock ? the if(previous stuff could leads to race condifitons, isn't it ?

**Comment by denis-ryzhkov** [comment]
Thanks for suggestions, @mikemoore13.

I selected to use milliseconds because it is the best precision available on all platforms. If the best one would be nanoseconds, whole lib would be unneeded - we could just use that int, unique enough, almost a quantum of time, ordered sequentially. If we go to seconds, or 10-second intervals like some IDs do, or minutes, or days - we will lose the benefits of precise timestamp. So let's keep using milliseconds which take 43 bits for 278 years - this is adjustable default value.

We don't have 64 bits, as this ID is intended to fit [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) on web platform, so we have 53 bits only, excluding negative ints, see [Design](https://pub.dev/packages/safe_int_id#design-and-usage) for details.

10 bits we have left are just 1024 possible values, not enough both for a counter and random if we want them be helpful. So we should either use `incId()` for counter-only (blocks when exhausted for a guarantee of local uniqueness), or original `getId()` for random (never blocks, so no guarantee, just probability).

Re race conditions: I don't see how they can happen both in this sync and async code, given https://dart.dev/language/concurrency

E.g. we called `incIdAsync()` 10000 times in a loop, stored all the futures in a list, and now are `await`-ing them all at once with https://api.dart.dev/stable/3.1.0/dart-async/Future/wait.html

First future that gets executed will produce ID in the sync way never reaching `await Future.delayed(...)` line inside. It will increment a counter from 0 to 1. Next future will do the same, incrementing from 1 to 2. And so on. If  millisecond switches, then counter gets reset, and sequential execution of futures continues. Once counter reaches 1024 by default, `await Future.delayed(...)` is executed for the first time, suspending this future and letting another future to start concurrently. If millisecond is still the same, it will reach `await` line too, and so on. Eventually one of futures will discover the millisecond has changed finally. It will reset the counter to zero and produce the ID in the sync way. It will also increment counter from 0 to 1, the next future - from 1 to 2, and so on. Anyway, only one future can be executed at the same time, so while they run concurrently, they do not run in parallel. It's like only one person serving multiple clients, one at a time, giving them tickets to wait with, while their order is prepared in background. In this case they order for a millisecond to get changed, and all wait for it, but cannot hurt each other.

Race condition would be possible if after `await` line they would make assumptions about a state of the counter or about millisecond, but they don't. They just read both millisecond and counter again, so no race happens here.

Please let me know if it makes sense or not.

**Comment by denis-ryzhkov** [comment]
No reply for 1 month, closing this issue.
